
// Additional translations for the Market page
// These are just the missing translations that we'll need

// For Albanian
"market.supply": "Oferta",
"market.demand": "Kërkesa",
"market.opportunity.index": "Indeksi i Mundësisë",
"market.regional.price.description": "Analizë e detajuar e çmimeve dhe ndryshimeve të tyre në rajonet kryesore të Shqipërisë.",
"market.highest.growth": "Rritja më e lartë",
"market.peak.season": "Sezoni i Pikut",
"market.low.season": "Sezoni i Ulët",
"market.may": "Maj",
"market.june": "Qershor",
"market.december": "Dhjetor",
"market.january": "Janar",
"market.years": "Vite",
"market.year": "Vit",
"market.retail": "Dyqane",
"market.office": "Zyra",
"region.suburbs": "Zona Periferike",
"analysis.important": "E Rëndësishme",
"market.listings": "Prona në Shitje",
"market.transactions": "Transaksione",
"market.price.index": "Indeksi i Çmimit",

// For English
"market.supply": "Supply",
"market.demand": "Demand",
"market.opportunity.index": "Opportunity Index",
"market.regional.price.description": "Detailed analysis of prices and their changes in key regions of Albania.",
"market.highest.growth": "Highest Growth",
"market.peak.season": "Peak Season",
"market.low.season": "Low Season",
"market.may": "May",
"market.june": "June",
"market.december": "December",
"market.january": "January",
"market.years": "Years",
"market.year": "Year",
"market.retail": "Retail",
"market.office": "Office",
"region.suburbs": "Suburban Areas",
"market.listings": "Property Listings",
"market.transactions": "Transactions",
"market.price.index": "Price Index",
