
import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define the translation types
interface Translations {
  [key: string]: string;
}

// Define the language context type
interface LanguageContextType {
  t: (key: string) => string;
  language: string;
  setLanguage: (lang: string) => void;
  toggleLanguage: () => void;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Additional translations for the Market page
const additionalTranslationsAlbanian: Translations = {
  "market.supply": "Oferta",
  "market.demand": "Kërkesa", 
  "market.opportunity.index": "Indeksi i Mundësisë",
  "market.regional.price.description": "Analizë e detajuar e çmimeve dhe ndryshimeve të tyre në rajonet kryesore të Shqipërisë.",
  "market.highest.growth": "Rritja më e lartë",
  "market.peak.season": "Sezoni i Pikut",
  "market.low.season": "Sezoni i Ulët",
  "market.may": "Maj",
  "market.june": "Qershor", 
  "market.december": "Dhjetor",
  "market.january": "Janar",
  "market.years": "Vite",
  "market.year": "Vit",
  "market.retail": "Dyqane",
  "market.office": "Zyra",
  "region.suburbs": "Zona Periferike",
  "analysis.important": "E Rëndësishme",
  "market.listings": "Prona në Shitje",
  "market.transactions": "Transaksione",
  "market.price.index": "Indeksi i Çmimit",
  "Tregu i Pronave": "Tregu i Pronave",
  "Analiza profesionale e tregut e përditësuar dy herë në ditë në orën 6 të mëngjesit dhe 6 të mbrëmjes": "Analiza profesionale e tregut e përditësuar dy herë në ditë në orën 6 të mëngjesit dhe 6 të mbrëmjes",
  "Prona Aktive": "Prona Aktive",
  "Çmimi Mesatar/m²": "Çmimi Mesatar/m²",
  "Rajoni më Aktiv": "Rajoni më Aktiv",
  "Indeksi i Mundësisë": "Indeksi i Mundësisë",
  "Nr. 1": "Nr. 1",
  "I Lartë": "I Lartë",
  "Përmbledhje": "Përmbledhje",
  "Trendet": "Trendet",
  "Rajonet": "Rajonet",
  "Investime": "Investime",
  "Përmbledhja e Tregut": "Përmbledhja e Tregut",
  "Analiza e detajuar e tregut të pronave në Shqipëri me fokus në Tiranë dhe qytetet kryesore": "Analiza e detajuar e tregut të pronave në Shqipëri me fokus në Tiranë dhe qytetet kryesore",
  "Trendet e Çmimeve": "Trendet e Çmimeve",
  "Analiza e thellë e lëvizjeve të çmimeve të pronave në të gjithë Shqipërinë": "Analiza e thellë e lëvizjeve të çmimeve të pronave në të gjithë Shqipërinë",
  "Analiza Rajonale": "Analiza Rajonale",
  "Krahasimi i çmimeve dhe analizës së detajuar për rajonet kryesore të Shqipërisë": "Krahasimi i çmimeve dhe analizës së detajuar për rajonet kryesore të Shqipërisë",
  "Analiza e Çmimeve Rajonale": "Analiza e Çmimeve Rajonale",
  "Mundësitë e Investimit": "Mundësitë e Investimit",
  "Kalkulime dhe analiza për investitorët që duan të investojnë në tregun shqiptar": "Kalkulime dhe analiza për investitorët që duan të investojnë në tregun shqiptar",
  "Analiza e Tregut të Pronave": "Analiza e Tregut të Pronave",
  "Të dhëna të detajuara për tregun e pronave në Shqipëri dhe rajonet kryesore": "Të dhëna të detajuara për tregun e pronave në Shqipëri dhe rajonet kryesore",
  "Shkarko të Dhënat": "Shkarko të Dhënat",
  "Printo": "Printo",
  "Ndaj": "Ndaj",
  "Filtro": "Filtro",
  "Përditësuar": "Përditësuar",
  "Rritje": "Rritje",
  "Albania": "Shqipëria",
  "Analiza e Avancuar": "Analiza e Avancuar",
  "Analizë e thellë dhe profesionale e tregut të pronave në Shqipëri me teknologji AI": "Analizë e thellë dhe profesionale e tregut të pronave në Shqipëri me teknologji AI",
  "Çmimi Mesatar": "Çmimi Mesatar",
  "Indeksi i Përballueshmerisë": "Indeksi i Përballueshmerisë",
  "Kthimi i Investimit": "Kthimi i Investimit",
  "Indeksi i Rrezikut": "Indeksi i Rrezikut",
  "I Mesëm": "I Mesëm",
  "Stabil": "Stabil",
  "Dinamika e Tregut": "Dinamika e Tregut",
  "Përballueshmerria": "Përballueshmerria",
  "Investimi": "Investimi",
  "Sezonshmëria": "Sezonshmëria",
  "Analiza e detajuar e lëvizjeve të tregut të pronave në Shqipëri me fokus në trendet aktuale": "Analiza e detajuar e lëvizjeve të tregut të pronave në Shqipëri me fokus në trendet aktuale",
  "Krahasimi i Tregut": "Krahasimi i Tregut",
  "Komerciale": "Komerciale",
  "Rezidenciale": "Rezidenciale",
  "Përzier": "Përzier",
  "Shpërndarja e Pronave": "Shpërndarja e Pronave",
  "Analiza e thelluar e përballueshmërisë së pronave në qytete të ndryshme të Shqipërisë": "Analiza e thelluar e përballueshmërisë së pronave në qytete të ndryshme të Shqipërisë",
  "Raporti Çmim/Të Ardhura": "Raporti Çmim/Të Ardhura",
  "Raporti": "Raporti",
  "Indeksi": "Indeksi",
  "Sa më i lartë indeksi, aq më e përballueshme është prona": "Sa më i lartë indeksi, aq më e përballueshme është prona",
  "Potenciali i Investimit": "Potenciali i Investimit",
  "Analiza e mundësive të investimit në tregun e pronave në Shqipëri": "Analiza e mundësive të investimit në tregun e pronave në Shqipëri",
  "ROI Vjetor": "ROI Vjetor",
  "ROI": "ROI",
  "Potenciali i Rritjes": "Potenciali i Rritjes",
  "Potenciali": "Potenciali",
  "Sezonshmëria e Tregut": "Sezonshmëria e Tregut",
  "Analiza e ndikimit të stinëve në tregun e pronave në Shqipëri": "Analiza e ndikimit të stinëve në tregun e pronave në Shqipëri",
  "Shitjet Sezonale": "Shitjet Sezonale",
  "Shitjet": "Shitjet",
  "Kërkesat": "Kërkesat",
  "Indeksi i Çmimit": "Indeksi i Çmimit",
  "Analiza Sezonale e Tregut": "Analiza Sezonale e Tregut",
  "Si ndryshon tregu i pronave përgjatë vitit": "Si ndryshon tregu i pronave përgjatë vitit",
  "Njoftime": "Njoftime",
  "Shitje": "Shitje",
  "Indeksi i çmimit": "Indeksi i çmimit",
  "Piku i njoftimeve": "Piku i njoftimeve",
  "Korrik": "Korrik",
  "Mesi i verës sheh më shumë njoftime të reja": "Mesi i verës sheh më shumë njoftime të reja",
  "Piku i shitjeve": "Piku i shitjeve",
  "Shitjet rriten nga fundi i pranverës deri në fund të verës": "Shitjet rriten nga fundi i pranverës deri në fund të verës",
  "Çmimet më të larta": "Çmimet më të larta",
  "Korrik-Gusht": "Korrik-Gusht",
  "Indeksi i çmimeve arrin pikun gjatë verës": "Indeksi i çmimeve arrin pikun gjatë verës",
  "analysis.seasonality": "Sezonshmëria",
  "analysis.seasonality.description": "Analiza e ndryshimeve sezonale në tregun e pronave"
};

const additionalTranslationsEnglish: Translations = {
  "market.supply": "Supply",
  "market.demand": "Demand",
  "market.opportunity.index": "Opportunity Index",
  "market.regional.price.description": "Detailed analysis of prices and their changes in key regions of Albania.",
  "market.highest.growth": "Highest Growth",
  "market.peak.season": "Peak Season",
  "market.low.season": "Low Season",
  "market.may": "May",
  "market.june": "June",
  "market.december": "December",
  "market.january": "January",
  "market.years": "Years",
  "market.year": "Year",
  "market.retail": "Retail",
  "market.office": "Office",
  "region.suburbs": "Suburban Areas",
  "market.listings": "Property Listings",
  "market.transactions": "Transactions",
  "market.price.index": "Price Index",
  "Tregu i Pronave": "Property Market",
  "Analiza profesionale e tregut e përditësuar dy herë në ditë në orën 6 të mëngjesit dhe 6 të mbrëmjes": "Professional market analysis updated twice daily at 6 AM and 6 PM",
  "Prona Aktive": "Active Properties",
  "Çmimi Mesatar/m²": "Average Price/m²",
  "Rajoni më Aktiv": "Most Active Region",
  "Indeksi i Mundësisë": "Opportunity Index",
  "Nr. 1": "No. 1",
  "I Lartë": "High",
  "Përmbledhje": "Overview",
  "Trendet": "Trends",
  "Rajonet": "Regions",
  "Investime": "Investments",
  "Përmbledhja e Tregut": "Market Overview",
  "Analiza e detajuar e tregut të pronave në Shqipëri me fokus në Tiranë dhe qytetet kryesore": "Detailed analysis of the property market in Albania with focus on Tirana and major cities",
  "Trendet e Çmimeve": "Price Trends",
  "Analiza e thellë e lëvizjeve të çmimeve të pronave në të gjithë Shqipërinë": "Deep analysis of property price movements throughout Albania",
  "Analiza Rajonale": "Regional Analysis",
  "Krahasimi i çmimeve dhe analizës së detajuar për rajonet kryesore të Shqipërisë": "Price comparison and detailed analysis for Albania's major regions",
  "Analiza e Çmimeve Rajonale": "Regional Price Analysis",
  "Mundësitë e Investimit": "Investment Opportunities",
  "Kalkulime dhe analiza për investitorët që duan të investojnë në tregun shqiptar": "Calculations and analysis for investors looking to invest in the Albanian market",
  "Analiza e Tregut të Pronave": "Property Market Analysis",
  "Të dhëna të detajuara për tregun e pronave në Shqipëri dhe rajonet kryesore": "Detailed data for the property market in Albania and major regions",
  "Shkarko të Dhënat": "Download Data",
  "Printo": "Print",
  "Ndaj": "Share",
  "Filtro": "Filter",
  "Përditësuar": "Updated",
  "Rritje": "Growth",
  "Albania": "Albania",
  "Analiza e Avancuar": "Advanced Analysis",
  "Analizë e thellë dhe profesionale e tregut të pronave në Shqipëri me teknologji AI": "Deep and professional analysis of the property market in Albania with AI technology",
  "Çmimi Mesatar": "Average Price",
  "Indeksi i Përballueshmerisë": "Affordability Index",
  "Kthimi i Investimit": "Return on Investment",
  "Indeksi i Rrezikut": "Risk Index",
  "I Mesëm": "Medium",
  "Stabil": "Stable",
  "Dinamika e Tregut": "Market Dynamics",
  "Përballueshmerria": "Affordability",
  "Investimi": "Investment",
  "Sezonshmëria": "Seasonality",
  "Analiza e detajuar e lëvizjeve të tregut të pronave në Shqipëri me fokus në trendet aktuale": "Detailed analysis of property market movements in Albania with focus on current trends",
  "Krahasimi i Tregut": "Market Comparison",
  "Komerciale": "Commercial",
  "Rezidenciale": "Residential",
  "Përzier": "Mixed",
  "Shpërndarja e Pronave": "Property Distribution",
  "Analiza e thelluar e përballueshmërisë së pronave në qytete të ndryshme të Shqipërisë": "In-depth analysis of property affordability in different cities of Albania",
  "Raporti Çmim/Të Ardhura": "Price to Income Ratio",
  "Raporti": "Ratio",
  "Indeksi": "Index",
  "Sa më i lartë indeksi, aq më e përballueshme është prona": "The higher the index, the more affordable the property",
  "Potenciali i Investimit": "Investment Potential",
  "Analiza e mundësive të investimit në tregun e pronave në Shqipëri": "Analysis of investment opportunities in Albania's property market",
  "ROI Vjetor": "Annual ROI",
  "ROI": "ROI",
  "Potenciali i Rritjes": "Growth Potential",
  "Potenciali": "Potential",
  "Sezonshmëria e Tregut": "Market Seasonality",
  "Analiza e ndikimit të stinëve në tregun e pronave në Shqipëri": "Analysis of seasonal impact on Albania's property market",
  "Shitjet Sezonale": "Seasonal Sales",
  "Shitjet": "Sales",
  "Kërkesat": "Inquiries",
  "Indeksi i Çmimit": "Price Index",
  "Analiza Sezonale e Tregut": "Seasonal Market Analysis",
  "Si ndryshon tregu i pronave përgjatë vitit": "How the property market changes throughout the year",
  "Njoftime": "Listings",
  "Shitje": "Sales",
  "Indeksi i çmimit": "Price Index",
  "Piku i njoftimeve": "Peak Listings",
  "Korrik": "July",
  "Mesi i verës sheh më shumë njoftime të reja": "Mid-summer sees more new listings",
  "Piku i shitjeve": "Peak Sales",
  "Shitjet rriten nga fundi i pranverës deri në fund të verës": "Sales increase from late spring to end of summer",
  "Çmimet më të larta": "Highest Prices",
  "Korrik-Gusht": "July-August",
  "Indeksi i çmimeve arrin pikun gjatë verës": "Price index reaches peak during summer",
  "analysis.seasonality": "Seasonality",
  "analysis.seasonality.description": "Analysis of seasonal changes in the property market"
};

// Define the main translations
const translations = {
  en: {
    // English translations
    'site.title': 'PronaStats',
    'site.tagline': 'Albanian Property Market Analytics',
    'nav.home': 'Home',
    'nav.market': 'Market',
    'nav.analysis': 'Analysis',
    'nav.about': 'About',
    'language': 'Language',
    'dashboard.stats': 'Dashboard Statistics',
    'dashboard.avg.price': 'Average Price',
    'dashboard.listings': 'Active Listings',
    'dashboard.yoy.change': 'Year-over-Year Change',
    'dashboard.last.updated': 'Last Updated',
    'dashboard.price.trends': 'Price Trends',
    'dashboard.property.types': 'Property Types by Region',
    'dashboard.regional.prices': 'Regional Prices',
    'dashboard.market.activity': 'Market Activity',
    'property.apartment': 'Apartments',
    'property.house': 'Houses',
    'property.land': 'Land',
    'property.commercial': 'Commercial',
    'region.tirana': 'Tirana',
    'region.durres': 'Durres',
    'region.vlore': 'Vlora',
    'region.sarande': 'Saranda',
    'region.shkoder': 'Shkodra',
    'market.insights': 'Market Insights',
    'market.trends.description': 'Monthly price trends across key Albanian regions, showing average price per square meter (€/m²).',
    'market.price.trends': 'Price Trends',
    'market.affordability': 'Affordability',
    'market.affordability.description': 'Key metrics showing housing affordability across major Albanian cities, including price-to-income ratios and mortgage trends.',
    'market.investment': 'Investment',
    'market.investment.description': 'Investment trends in the Albanian property market, including origin of capital and potential return metrics.',
    'market.price.income.ratio': 'Price to Income Ratio',
    'market.price.income.explanation': 'Number of years of median income needed to purchase a median-priced property.',
    'market.mortgage.trends': 'Mortgage Trends',
    'market.mortgage.rate': 'Average Rate (%)',
    'market.mortgage.volume': 'Number of Mortgages',
    'market.investment.origin': 'Investment Origin',
    'market.domestic.investors': 'Domestic Investors',
    'market.foreign.investors': 'Foreign Investors',
    'market.price.to.rent': 'Price to Rent Ratio',
    'market.price.to.rent.explanation': 'Higher ratios indicate better opportunities for renting rather than buying.',
    'market.quarterly.change': 'Quarterly Change',
    'market.news': 'Market News',
    'market.news.list': 'News List',
    'market.news.featured': 'Featured News',
    'market.featured': 'Featured Story',
    'filter.results': 'Filter Results',
    'expand.view': 'Expand All',
    'collapse.view': 'Collapse All',
    'read.more': 'Read More',
    'view.more': 'View Article',
    'source': 'Source',
    'no.data': 'No data available',
    'all': 'All',
    'properties.location': 'Location',
    'about.data.sources': 'Data Sources',
    'about.disclaimer.text': 'All market data is for informational purposes only',
    'nav.dashboard': 'Dashboard',
    'dashboard.title': 'Property Market Dashboard',
    'dashboard.subtitle': 'Real-time analytics and market trends',
    'download.data': 'Download Data',
    'print': 'Print',
    'share': 'Share',
    'year.over.year': 'Year-over-Year',
    'dashboard.total.listings': 'Total Listings',
    'sqm': 'per m²',
    'dashboard.price.sqm': 'Price per m²',
    'market.overview': 'Market Overview',
    'dashboard.developer.insights': 'Developer Insights',
    'dashboard.investor.metrics': 'Investor Metrics',
    'property.types': 'Property Types',
    'property.luxury': 'Luxury',
    'dashboard.price.regions': 'Regional Price Comparison',
    'high.opportunity': 'High Opportunity',
    'dashboard.construction.costs': 'Construction Costs',
    'market.development.costs': 'Development Costs & Trends',
    'property.residential': 'Residential',
    'market.economy': 'Economy',
    'market.midrange': 'Mid-Range',
    'market.standard': 'Standard',
    'market.premium': 'Premium',
    'analysis.building.permits': 'Building Permits',
    'analysis.development.opportunities': 'Development Opportunities',
    'crawler.last_update': 'Last Update',
    'region.center.tirana': 'Center',
    'crawler.coast': 'Coastal Region',
    'medium.opportunity': 'Medium Opportunity',
    'analysis.zoning.regulations': 'Zoning Regulations',
    'analysis.urban.planning': 'Urban Planning',
    'analysis.update': 'Update',
    'analysis.urban.planning.description': 'Latest urban planning guidelines and zoning regulations for major cities',
    'analysis.regulatory.landscape': 'Regulatory Updates',
    'analysis.regulatory.description': 'Recent changes in property regulations and development laws',
    'analysis.roi.analysis': 'ROI Analysis',
    'analysis.short.term': 'Short Term',
    'analysis.medium.term': 'Medium Term',
    'analysis.long.term': 'Long Term',
    'market.rental.yield': 'Rental Yield',
    'analysis.price.projections': 'Price Projections',
    'quarter.over.quarter': 'Quarter-over-Quarter',
    'Albanian Banks Mortgage Comparison': 'Albanian Banks Mortgage Comparison',
    'Compare mortgage rates, terms, and features from leading Albanian banks': 'Compare mortgage rates, terms, and features from leading Albanian banks',
    'Best Rates': 'Best Rates',
    'Top Rated': 'Top Rated',
    'Fastest Approval': 'Fastest Approval',
    'Best Rate': 'Best Rate',
    'Fastest': 'Fastest',
    'Interest Rate': 'Interest Rate',
    'Down Payment': 'Down Payment',
    'Max Term': 'Max Term',
    'Processing Time': 'Processing Time',
    'min': 'min',
    'years': 'years',
    'days': 'days',
    'Offers': 'Offers',
    'Requirements': 'Requirements',
    'Contact': 'Contact',
    'more': 'more',
    'Quick Comparison': 'Quick Comparison',
    'Bank': 'Bank',
    'Min Rate': 'Min Rate',
    'Processing': 'Processing',
    'Rating': 'Rating',
    'Select Region': 'Select Region',
    'All Regions': 'All Regions',
    'Prices': 'Prices',
    'Changes': 'Changes',
    'Activity': 'Activity',
    'Regional Price Comparison': 'Regional Price Comparison',
    'Quarterly Price Changes': 'Quarterly Price Changes',
    'Market Activity Levels': 'Market Activity Levels',
    'Price per m²': 'Price per m²',
    'Change': 'Change',
    'Properties': 'Properties',
    'Luxury': 'Luxury',
    'Avg': 'Avg',
    ...additionalTranslationsEnglish
  },
  sq: {
    // Albanian translations  
    'site.title': 'PronaStats',
    'site.tagline': 'Analiza e Tregut të Pronave në Shqipëri',
    'nav.home': 'Kryefaqja',
    'nav.market': 'Tregu',
    'nav.analysis': 'Analiza',
    'nav.about': 'Rreth Nesh',
    'language': 'Gjuha',
    'dashboard.stats': 'Statistikat e Panelit',
    'dashboard.avg.price': 'Çmimi Mesatar',
    'dashboard.listings': 'Prona Aktive',
    'dashboard.yoy.change': 'Ndryshimi vjetor',
    'dashboard.last.updated': 'Përditësimi i Fundit',
    'dashboard.price.trends': 'Trendet e Çmimeve',
    'dashboard.property.types': 'Llojet e Pronave sipas Rajonit',
    'dashboard.regional.prices': 'Çmimet Rajonale',
    'dashboard.market.activity': 'Aktiviteti i Tregut',
    'property.apartment': 'Apartamente',
    'property.house': 'Shtëpi',
    'property.land': 'Truall',
    'property.commercial': 'Komerciale',
    'region.tirana': 'Tiranë',
    'region.durres': 'Durrës',
    'region.vlore': 'Vlorë',
    'region.sarande': 'Sarandë',
    'region.shkoder': 'Shkodër',
    'market.insights': 'Pikëpamje të Tregut',
    'market.trends.description': 'Trendet mujore të çmimeve në rajonet kryesore të Shqipërisë, duke treguar çmimin mesatar për metër katror (€/m²).',
    'market.price.trends': 'Trendet e Çmimeve',
    'market.affordability': 'Përballueshmëria',
    'market.affordability.description': 'Metrika kryesore që tregojnë përballueshmërinë e banesave në qytetet kryesore të Shqipërisë, përfshirë raportet çmim-të-ardhura dhe trendet e kredive hipotekare.',
    'market.investment': 'Investime',
    'market.investment.description': 'Trendet e investimeve në tregun e pronave në Shqipëri, përfshirë origjinën e kapitalit dhe metrikat potenciale të kthimit.',
    'market.price.income.ratio': 'Raporti Çmim ndaj të Ardhurave',
    'market.price.income.explanation': 'Numri i viteve të të ardhurave mesatare të nevojshme për të blerë një pronë me çmim mesatar.',
    'market.mortgage.trends': 'Trendet e Kredive Hipotekare',
    'market.mortgage.rate': 'Norma Mesatare (%)',
    'market.mortgage.volume': 'Numri i Kredive',
    'market.investment.origin': 'Origjina e Investimeve',
    'market.domestic.investors': 'Investitorë Vendas',
    'market.foreign.investors': 'Investitorë të Huaj',
    'market.price.to.rent': 'Raporti Çmim ndaj Qirasë',
    'market.price.to.rent.explanation': 'Raportet më të larta tregojnë mundësi më të mira për qira sesa për blerje.',
    'market.quarterly.change': 'Ndryshimi Tremujor',
    'market.news': 'Lajme të Tregut',
    'market.news.list': 'Lista e Lajmeve',
    'market.news.featured': 'Lajme të Zgjedhura',
    'market.featured': 'Artikull i Zgjedhur',
    'filter.results': 'Filtro Rezultatet',
    'expand.view': 'Zgjero të Gjitha',
    'collapse.view': 'Mbyll të Gjitha',
    'read.more': 'Lexo Më Shumë',
    'view.more': 'Shiko Artikullin',
    'source': 'Burimi',
    'no.data': 'Nuk ka të dhëna',
    'all': 'Të Gjitha',
    'properties.location': 'Vendndodhja',
    'about.data.sources': 'Burimet e të Dhënave',
    'about.disclaimer.text': 'Të gjitha të dhënat e tregut janë vetëm për qëllime informative',
    'nav.dashboard': 'Paneli',
    'dashboard.title': 'Paneli i Tregut të Pronave',
    'dashboard.subtitle': 'Analiza në kohë reale dhe trendët e tregut',
    'download.data': 'Shkarko të Dhënat',
    'print': 'Printo',
    'share': 'Ndaj',
    'year.over.year': 'Vit pas Viti',
    'dashboard.total.listings': 'Totali i Pronave',
    'sqm': 'për m²',
    'dashboard.price.sqm': 'Çmimi për m²',
    'market.overview': 'Përmbledhje e Tregut',
    'dashboard.developer.insights': 'Informacione për Zhvilluesit',
    'dashboard.investor.metrics': 'Metrika për Investitorët',
    'property.types': 'Llojet e Pronave',
    'property.luxury': 'Luksoze',
    'dashboard.price.regions': 'Krahasimi i Çmimeve Rajonale',
    'high.opportunity': 'Mundësi e Lartë',
    'dashboard.construction.costs': 'Kostot e Ndërtimit',
    'market.development.costs': 'Kostot dhe Trendet e Zhvillimit',
    'property.residential': 'Rezidenciale',
    'market.economy': 'Ekonomike',
    'market.midrange': 'Mesatare',
    'market.standard': 'Standarde',
    'market.premium': 'Premium',
    'analysis.building.permits': 'Lejet e Ndërtimit',
    'analysis.development.opportunities': 'Mundësitë e Zhvillimit',
    'crawler.last_update': 'Përditësimi i Fundit',
    'region.center.tirana': 'Qendër',
    'crawler.coast': 'Rajon Bregdetar',
    'medium.opportunity': 'Mundësi Mesatare',
    'analysis.zoning.regulations': 'Rregulloret e Zonimit',
    'analysis.urban.planning': 'Planifikimi Urban',
    'analysis.update': 'Përditësim',
    'analysis.urban.planning.description': 'Udhëzimet e fundit të planifikimit urban dhe rregulloret e zonimit për qytetet kryesore',
    'analysis.regulatory.landscape': 'Përditësime Rregullatore',
    'analysis.regulatory.description': 'Ndryshimet e fundit në rregulloret e pronave dhe ligjet e zhvillimit',
    'analysis.roi.analysis': 'Analiza ROI',
    'analysis.short.term': 'Afatshkurtër',
    'analysis.medium.term': 'Afatmesëm',
    'analysis.long.term': 'Afatgjatë',
    'market.rental.yield': 'Rendimenti i Qirasë',
    'analysis.price.projections': 'Projeksionet e Çmimeve',
    'quarter.over.quarter': 'Tremujor pas Tremujori',
    'Albanian Banks Mortgage Comparison': 'Krahasimi i Kredive Hipotekare në Bankat Shqiptare',
    'Compare mortgage rates, terms, and features from leading Albanian banks': 'Krahasoni normat e kredive, afatet dhe karakteristikat nga bankat kryesore shqiptare',
    'Best Rates': 'Normat më të Mira',
    'Top Rated': 'Më të Vlerësuarat',
    'Fastest Approval': 'Miratimi më i Shpejtë',
    'Best Rate': 'Norma më e Mirë',
    'Fastest': 'Më i Shpejti',
    'Interest Rate': 'Norma e Interesit',
    'Down Payment': 'Pagesa Fillestare',
    'Max Term': 'Afati Maksimal',
    'Processing Time': 'Koha e Procesimit',
    'min': 'min',
    'years': 'vjet',
    'days': 'ditë',
    'Offers': 'Ofertat',
    'Requirements': 'Kërkesat',
    'Contact': 'Kontakti',
    'more': 'më shumë',
    'Quick Comparison': 'Krahasim i Shpejtë',
    'Bank': 'Banka',
    'Min Rate': 'Norma Min',
    'Processing': 'Procesimi',
    'Rating': 'Vlerësimi',
    'Select Region': 'Zgjidh Rajonin',
    'All Regions': 'Të Gjitha Rajonet',
    'Prices': 'Çmimet',
    'Changes': 'Ndryshimet',
    'Activity': 'Aktiviteti',
    'Regional Price Comparison': 'Krahasimi i Çmimeve Rajonale',
    'Quarterly Price Changes': 'Ndryshimet Tremujore të Çmimeve',
    'Market Activity Levels': 'Nivelet e Aktivitetit të Tregut',
    'Price per m²': 'Çmimi për m²',
    'Change': 'Ndryshim',
    'Properties': 'Prona',
    'Luxury': 'Luksoze',
    'Avg': 'Mes',
    ...additionalTranslationsAlbanian
  }
};

// Create the provider component
export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Changed default language to Albanian (sq)
  const [language, setLanguage] = useState<string>('sq');
  
  // Translation function
  const t = (key: string): string => {
    const currentTranslations = translations[language as keyof typeof translations] || translations.sq;
    return currentTranslations[key] || key;
  };

  // Toggle function to switch between languages
  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === 'sq' ? 'en' : 'sq');
  };
  
  return (
    <LanguageContext.Provider value={{ t, language, setLanguage, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using the language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
