// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzfaswkmxdawrnbhjmfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6ZmFzd2tteGRhd3JuYmhqbWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzUyMDQsImV4cCI6MjA2NTUxMTIwNH0.0o-pWOsXAdysyHo-oio1Nq17O0tfUR9oL7cxD_oGnOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);